//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wikihotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_hotel { get; set; }
        public System.DateTime checkin_date { get; set; }
        public string checkout_date { get; set; }
        public Nullable<int> day_stay { get; set; }
    }
}
