//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wikihotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<double> price { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<int> @class { get; set; }
    }
}
