//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace hotelkulo_com
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class db_hotelEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new db_hotelEntities object using the connection string found in the 'db_hotelEntities' section of the application configuration file.
        /// </summary>
        public db_hotelEntities() : base("name=db_hotelEntities", "db_hotelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db_hotelEntities object.
        /// </summary>
        public db_hotelEntities(string connectionString) : base(connectionString, "db_hotelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db_hotelEntities object.
        /// </summary>
        public db_hotelEntities(EntityConnection connection) : base(connection, "db_hotelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<hotel> hotels
        {
            get
            {
                if ((_hotels == null))
                {
                    _hotels = base.CreateObjectSet<hotel>("hotels");
                }
                return _hotels;
            }
        }
        private ObjectSet<hotel> _hotels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<booking> bookings
        {
            get
            {
                if ((_bookings == null))
                {
                    _bookings = base.CreateObjectSet<booking>("bookings");
                }
                return _bookings;
            }
        }
        private ObjectSet<booking> _bookings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the hotels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohotels(hotel hotel)
        {
            base.AddObject("hotels", hotel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the bookings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobookings(booking booking)
        {
            base.AddObject("bookings", booking);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_hotelModel", Name="booking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class booking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new booking object.
        /// </summary>
        /// <param name="checkin_date">Initial value of the checkin_date property.</param>
        public static booking Createbooking(global::System.DateTime checkin_date)
        {
            booking booking = new booking();
            booking.checkin_date = checkin_date;
            return booking;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value, "id");
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private Nullable<global::System.Int32> _id;
        partial void OnidChanging(Nullable<global::System.Int32> value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                Onid_userChanging(value);
                ReportPropertyChanging("id_user");
                _id_user = StructuralObject.SetValidValue(value, "id_user");
                ReportPropertyChanged("id_user");
                Onid_userChanged();
            }
        }
        private Nullable<global::System.Int32> _id_user;
        partial void Onid_userChanging(Nullable<global::System.Int32> value);
        partial void Onid_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_hotel
        {
            get
            {
                return _id_hotel;
            }
            set
            {
                Onid_hotelChanging(value);
                ReportPropertyChanging("id_hotel");
                _id_hotel = StructuralObject.SetValidValue(value, "id_hotel");
                ReportPropertyChanged("id_hotel");
                Onid_hotelChanged();
            }
        }
        private Nullable<global::System.Int32> _id_hotel;
        partial void Onid_hotelChanging(Nullable<global::System.Int32> value);
        partial void Onid_hotelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime checkin_date
        {
            get
            {
                return _checkin_date;
            }
            set
            {
                if (_checkin_date != value)
                {
                    Oncheckin_dateChanging(value);
                    ReportPropertyChanging("checkin_date");
                    _checkin_date = StructuralObject.SetValidValue(value, "checkin_date");
                    ReportPropertyChanged("checkin_date");
                    Oncheckin_dateChanged();
                }
            }
        }
        private global::System.DateTime _checkin_date;
        partial void Oncheckin_dateChanging(global::System.DateTime value);
        partial void Oncheckin_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String checkout_date
        {
            get
            {
                return _checkout_date;
            }
            set
            {
                Oncheckout_dateChanging(value);
                ReportPropertyChanging("checkout_date");
                _checkout_date = StructuralObject.SetValidValue(value, true, "checkout_date");
                ReportPropertyChanged("checkout_date");
                Oncheckout_dateChanged();
            }
        }
        private global::System.String _checkout_date;
        partial void Oncheckout_dateChanging(global::System.String value);
        partial void Oncheckout_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> day_stay
        {
            get
            {
                return _day_stay;
            }
            set
            {
                Onday_stayChanging(value);
                ReportPropertyChanging("day_stay");
                _day_stay = StructuralObject.SetValidValue(value, "day_stay");
                ReportPropertyChanged("day_stay");
                Onday_stayChanged();
            }
        }
        private Nullable<global::System.Int32> _day_stay;
        partial void Onday_stayChanging(Nullable<global::System.Int32> value);
        partial void Onday_stayChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_hotelModel", Name="hotel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class hotel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new hotel object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static hotel Createhotel(global::System.Int32 id)
        {
            hotel hotel = new hotel();
            hotel.id = id;
            return hotel;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value, "price");
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private Nullable<global::System.Double> _price;
        partial void OnpriceChanging(Nullable<global::System.Double> value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true, "city");
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, true, "country");
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> rating
        {
            get
            {
                return _rating;
            }
            set
            {
                OnratingChanging(value);
                ReportPropertyChanging("rating");
                _rating = StructuralObject.SetValidValue(value, "rating");
                ReportPropertyChanged("rating");
                OnratingChanged();
            }
        }
        private Nullable<global::System.Double> _rating;
        partial void OnratingChanging(Nullable<global::System.Double> value);
        partial void OnratingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> @class
        {
            get
            {
                return _class;
            }
            set
            {
                OnclassChanging(value);
                ReportPropertyChanging("class");
                _class = StructuralObject.SetValidValue(value, "class");
                ReportPropertyChanged("class");
                OnclassChanged();
            }
        }
        private Nullable<global::System.Int32> _class;
        partial void OnclassChanging(Nullable<global::System.Int32> value);
        partial void OnclassChanged();

        #endregion

    }

    #endregion

}
