//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asuransi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_asuransiEntities : DbContext
    {
        public db_asuransiEntities()
            : base("name=db_asuransiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Asuransi_nasabah> Asuransi_nasabah { get; set; }
        public virtual DbSet<Jenis_asuransi> Jenis_asuransi { get; set; }
        public virtual DbSet<Nasabah> Nasabah { get; set; }
        public virtual DbSet<Pembayaran_klaim> Pembayaran_klaim { get; set; }
        public virtual DbSet<Setoran> Setoran { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
