//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asuransi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nasabah
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nasabah()
        {
            this.Asuransi_nasabah = new HashSet<Asuransi_nasabah>();
            this.Pembayaran_klaim = new HashSet<Pembayaran_klaim>();
            this.Setoran = new HashSet<Setoran>();
        }
    
        public int id_nasabah { get; set; }
        public int id_asuransi { get; set; }
        public string nama_nasabah { get; set; }
        public int no_identitas { get; set; }
        public string tempat_lahir { get; set; }
        public System.DateTime tanggal_lahir { get; set; }
        public string jenis_kelamin { get; set; }
        public string status { get; set; }
        public string pekerjaan { get; set; }
        public string penghasilan { get; set; }
        public string alamat { get; set; }
        public int no_telp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asuransi_nasabah> Asuransi_nasabah { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pembayaran_klaim> Pembayaran_klaim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setoran> Setoran { get; set; }
    }
}
